# Generated by Django 3.0.3 on 2020-03-03 15:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0002_auto_20200303_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='tags')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='links.Link')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
    ]
